# Generated by Django 3.1.5 on 2021-01-24 16:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('DisplayName', models.CharField(max_length=50)),
                ('SpotifyDisplayName', models.CharField(max_length=150, null=True)),
                ('SpotifyUserId', models.CharField(max_length=150, null=True, unique=True)),
                ('SpotifyAuthToken', models.CharField(max_length=200, null=True)),
                ('ZipCode', models.CharField(max_length=10, null=True)),
                ('ProfilePic', models.ImageField(null=True, upload_to='')),
                ('META_StartDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('META_EndDate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('MatchId', models.IntegerField(primary_key=True, serialize=False)),
                ('AcceptedByUser1', models.BooleanField(default=False)),
                ('AcceptedByUser2', models.BooleanField(default=False)),
                ('META_StartDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('META_EndDate', models.DateTimeField(null=True)),
                ('User1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User1', to='Meetify.user_info')),
                ('User2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User2', to='Meetify.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('MessageNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Text', models.CharField(max_length=300)),
                ('META_StartDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('META_EndDate', models.DateTimeField(null=True)),
                ('MatchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meetify.matches')),
                ('SenderUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('MatchId', 'MessageNumber')},
            },
        ),
        migrations.CreateModel(
            name='Liked_Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songUri', models.CharField(max_length=200)),
                ('META_StartDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('META_EndDate', models.DateTimeField(null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meetify.user_info')),
            ],
            options={
                'unique_together': {('userId', 'songUri')},
            },
        ),
    ]