# Generated by Django 3.1.5 on 2021-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetify', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='META_EndDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='META_LastActive',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='META_StartDate',
            field=models.DateTimeField(null=True),
        ),
    ]
