# Generated by Django 3.1.5 on 2021-02-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetify', '0002_auto_20210213_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
