# Generated by Django 3.1.5 on 2021-02-10 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Meetify', '0002_auto_20210208_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acousticness', models.DecimalField(decimal_places=2, max_digits=7)),
                ('danceability', models.DecimalField(decimal_places=2, max_digits=7)),
                ('energy', models.DecimalField(decimal_places=2, max_digits=7)),
                ('instrumentalness', models.DecimalField(decimal_places=2, max_digits=7)),
                ('loudness', models.DecimalField(decimal_places=2, max_digits=7)),
                ('speechiness', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tempo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valence', models.DecimalField(decimal_places=2, max_digits=7)),
                ('number_of_liked_songs', models.IntegerField()),
                ('META_StartDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('META_EndDate', models.DateTimeField(null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meetify.user_info')),
            ],
        ),
    ]
