# Generated by Django 3.1.5 on 2021-02-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetify', '0003_user_info_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='MessageNumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
