# Generated by Django 3.1.5 on 2021-01-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetify', '0003_auto_20210118_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ProfilePic',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
