# Generated by Django 3.1.5 on 2021-03-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetify', '0004_auto_20210220_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='ProfilePic',
        ),
        migrations.AddField(
            model_name='user_info',
            name='ProfilePicURL',
            field=models.URLField(null=True),
        ),
    ]
