# Generated by Django 3.1.5 on 2021-01-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetify', '0004_users_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ProfilePic',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
