# Generated by Django 3.1.5 on 2021-01-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetify', '0005_auto_20210118_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=200),
        ),
    ]
