# Generated by Django 3.1.5 on 2021-01-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetify', '0006_auto_20210118_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.BinaryField(max_length=200),
        ),
    ]
