# Generated by Django 3.1.5 on 2021-01-21 01:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Meetify', '0009_auto_20210120_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Info',
        ),
    ]
