# Generated by Django 3.1.2 on 2020-10-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_liked_songs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liked_Songs',
            new_name='LikedSongs',
        ),
    ]
