# Generated by Django 3.1.2 on 2020-10-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201003_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedSongs',
            new_name='Liked_Songs',
        ),
    ]
